version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_PASSWORD}
      MYSQL_DATABASE: playdb
    ports:
      - "3307:3306"
    networks:
      - play-network

  play-app:
    build: .
    image: play-java-app
    ports:
      - "9000:9000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: playdb
      DB_USER: ${MY_USERNAME}
      DB_PASSWORD: ${MY_PASSWORD}
    depends_on:
      - db
    networks:
      - play-network

networks:
  play-network:
    driver: bridge
