# Configuração do banco de dados para Ebean usando MySQL
#db.default.driver=com.mysql.cj.jdbc.Driver
#db.default.url="jdbc:mysql://127.0.0.1:3306/playdb?useSSL=false"
#db.default.username=root
#db.default.password=1234
#db.default.logSql=true
play.http.secret.key="kJf8&dU9q3LmNq#hT1^gY5rX9mQb7eF!"


ebean.default = ["models.*"]

# Evolutions (Database Schema Evolution)
play.evolutions.autoApply=false
play.evolutions.autoApplyDowns=false

# Logging configuration
logger.application=INFO

# Content Security Policy (CSP) configuration
play.filters.headers.contentSecurityPolicy="default-src 'self'; script-src 'self' https://code.jquery.com"

# More detailed CSP configuration using directives
play.filters.csp {
  header="Content-Security-Policy"
  directives {
    default-src=["'self'"] // Only allow content from the same origin
    script-src=["'self'", "https://code.jquery.com", "'nonce-{nonce}'"] // Allow scripts from self and jQuery CDN, with nonce for inline scripts
    style-src=["'self'", "'unsafe-inline'"] // Allow styles from self and inline styles
    img-src=["'self'", "data:"] // Allow images from self and data URIs
  }
}

# Cross-Origin Resource Sharing (CORS) configuration
play.filters.cors.allowedOrigins=["http://localhost:9000","http://127.0.0.1:9000"] // Only allow requests from this origin

# Evolutions (Database Schema Evolution)
play.evolutions.autoApply=false
play.evolutions.autoApplyDowns=false


play.modules.disable += "play.api.db.evolutions.EvolutionsModule"

play.filters.disabled+="play.filters.headers.SecurityHeadersFilter"
play.filters.disabled+=play.filters.csrf.CSRFFilter
play.filters.disabled+=play.filters.hosts.AllowedHostsFilter


#play.filters.enabled += "play.filters.csrf.CSRFFilter"

# Configuração da JPA
#play.db.jpa {
#  default = "defaultPersistenceUnit"
#  defaultPersistenceUnit = {
#    provider = "org.hibernate.jpa.HibernatePersistenceProvider"
#    jndiName = "DefaultDS"
#    properties {
#      hibernate.dialect = "org.hibernate.dialect.MySQL8Dialect"
#      hibernate.hbm2ddl.auto = "update"
#    }
#  }
#}



logger.ebean.level=DEBUG
logger.io.ebean.level=DEBUG
logger.datasource.level=DEBUG
logger.application=DEBUG
