name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar variáveis de ambiente usando secrets do GitHub
      - name: Set environment variables
        run: |
          echo "DB_DRIVER=com.mysql.cj.jdbc.Driver" >> $GITHUB_ENV
          echo "DB_URL=jdbc:mysql://127.0.0.1:3306/playdb?useSSL=false" >> $GITHUB_ENV
          echo "MY_USERNAME=${{ secrets.MY_USERNAME }}" >> $GITHUB_ENV
          echo "MY_PASSWORD=${{ secrets.MY_PASSWORD }}" >> $GITHUB_ENV

      # Fazer build da imagem Docker com as variáveis de ambiente
      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      # Testar a aplicação rodando o container com variáveis de ambiente
      - name: Run Docker container
        run: |
          docker run -e DB_DRIVER=$DB_DRIVER -e DB_URL=$DB_URL -e MY_USERNAME=$MY_USERNAME -e MY_PASSWORD=$MY_PASSWORD my-app-image
